---
title: Google Cloud
subtitle: GCP for Archive and Analysis
---

#### [**National PAM SI Cloud Repo**](https://nmfs-ost.github.io/PAM-Cloud/){target="_blank"}**:** more details on cloud storage and processing from the cloud team

## **NWFSC GCP Buckets:** 

#### [nwfsc-1](https://console.cloud.google.com/storage/browser/nwfsc-1;tab=objects?cloudshell=true&inv=1&invt=AbrESg&project=ggn-nmfs-pamdata-prod-1&prefix=&forceOnObjectsSortingFiltering=false) : Salish Sea raw audio data

#### [nwfsc-2](https://console.cloud.google.com/storage/browser/nwfsc-2;tab=objects?cloudshell=true&inv=1&invt=AbrESg&project=ggn-nmfs-pamdata-prod-1&prefix=&forceOnObjectsSortingFiltering=false) : Coastal raw audio data


## Accessing Data

Check the [archive spreadsheet](https://docs.google.com/spreadsheets/d/1bNu1GPOmyn3CRZ70Mnq4ZZmH7n7ZwIASIlcZD6zWa-k/edit?usp=sharing) to see if the dataset you are interested in accessing is available in the [SWFSC-SAEL bucket](https://console.cloud.google.com/storage/browser/swfsc-1;tab=objects?forceOnBucketsSortingFiltering=true&project=ggn-nmfs-pamdata-prod-1&prefix=&forceOnObjectsSortingFiltering=false).



## Cloud Storage

### Manual Upload

1.  Open [SWFSC bucket](https://console.cloud.google.com/storage/browser/swfsc-1;tab=objects?forceOnBucketsSortingFiltering=true&project=ggn-nmfs-pamdata-prod-1&prefix=&forceOnObjectsSortingFiltering=false) in GCP console

2.  Select Upload (Upload files or Upload folder) and navigate to the data you want to upload

3.  Click "Upload"

    ::: callout-caution
    ## Large data files or datasets may crash GCP with this upload method. If you would like to upload large amounts of data, do so through the GCP sdk/gsutil options below
    :::

### sdk/gsutil Set-Up

1.  Download the [Google Cloud CLI installer](https://cloud.google.com/sdk/docs/install-sdk) and install Cloud SDK on your computer
2.  Open the 'Google Cloud SDK Shell Terminal', follow the prompts, and select ***'ggn-nmfs-pamdata-prod-1'*** as your project

### sdk/gsutil Upload

1.  Open the 'Google Cloud SDK Shell Terminal'
2.  Enter the follow command to upload files to the GCP: `gsutil -m cp -r [source pathway to files to be uploaded/] gs:[destination pathway to folder on bucket/]`
    -   SAEL ADRIFT Example `"gsutil -m cp -r E:\DATA\LEG_2\RECORDINGS\CalCurCEAS_004 gs://swfsc-1/drifting_recorder/CalCurCEAS_2024"`
3.  Processing should start, wait for terminal prompt to update then refresh the SWFSC bucket website to see your uploaded data

### Automated sdk/gsutil Upload

You can use the following R script to automatically run the above command and bulk upload data from a source. R script available [here](https://github.com/SAEL-SWFSC/SAEL-lab-manual/blob/main/Scripts/GoogleCloudBulkUpload.R){target="_blank"}. This script is set up to only run from 6 pm to 6 am on weekdays and full time on weekends, to avoid excess network traffic.

```{r}
#| echo: false
#| results: asis

#| file: ../Scripts/GoogleCloudBulkUpload.R

# Read in the script and output it as a formatted code block
script_path <- "../Scripts/GoogleCloudBulkUpload.R"  # Adjust path as neededAdd commentMore actions
code <- readLines(script_path)
cat("```r\n", paste(code, collapse = "\n"), "\n```")
```

### More information on Cloud Storage

See the [PAM SI Cloud Storage](https://nmfs-ost.github.io/PAM-Cloud/content/Cloud.Storage.html){target="_blank"} website for more information and troubleshooting tips

## Cloud Processing

Cloud based processing is now available through google workstations using the data you upload to GCP. SAEL has not began processing in the cloud but you can follow the steps below to establish a windows virtual machine (workstation) and access the [existing cloud based software](https://docs.google.com/spreadsheets/d/1b60mbrTqpHH29vN8u6KcWdABWEfdkRhZTSwYcdnMJUM/edit?gid=1389628961#gid=1389628961){target="_blank"}

### PAM Windows Workstation

Follow the [detailed directions here](https://nmfs-ost.github.io/PAM-Cloud/content/PAM.ww.html){target="_blank"} to establish a windows workstation

### More Information on Cloud Processing

See the [PAM SI Cloud Processing](https://nmfs-ost.github.io/PAM-Cloud/content/Cloud.Processing.html){target="_blank"} website for more information and troubleshooting tips